apiVersion: helm.toolkit.fluxcd.io/v1beta1
kind: HelmRelease
metadata:
  name: helm-postgre
  namespace: psac-gitops
spec:
  releaseName: postgresql         # The release name used by Helm
  interval: 1m                    # How often to check for updates
  chart:
    spec:
      chart: postgresql           # Name of the chart to install
      repository: https://charts.bitnami.com/bitnami  # Bitnami repository URL
  values:
    global:
      postgresql:
        postgresqlUsername: 
          valueFrom:
            secretKeyRef:
              name: postgresql-secret       # Name of the secret
              key: postgresql-username      # Key in the secret
        postgresqlPassword: 
          valueFrom:
            secretKeyRef:
              name: postgresql-secret       # Name of the secret
              key: postgresql-password      # Key in the secret
        postgresqlDatabase: psacdb      # Database name to create
    service:
      type: NodePort                       # Service type
      port: 5432
      nodePort: 30000                            # Port for the PostgreSQL service
    primary:
      persistence:
        enabled: true                       # Enable persistence
        size: 8Gi                           # Size of persistent volume
