apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  releaseName: mongodb
  interval: 1h
  chart:
    spec:
      chart: mongodb
      version: 16.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: infrastructure
  values:
    auth:
      databases: [testdb]
      usernames: [admin]
      passwords: [admin123]
    persistence:
      enabled: true
      size: 1Gi
    service:
      type: NodePort
      ports:
        mongodb: 27017
      nodePorts: 
        mongodb: 30010
