apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  labels:
    app: example-app
  namespace: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: ghcr.io/ben3dek/bened3k-psac/example-app:v1.0.1 # {"$imagepolicy": "example-app:example-app"}
        ports:
        - containerPort: 5000
