apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: example-app
  namespace: example-app
spec:
  imageRepositoryRef:
    name: example-app
    namespace: infrastructure
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: infrastructure
  policy:
    semver:
      range: 1.x.x