apiVersion: v1
kind: Service
metadata:
  namespace: example-app
  name: example-app
spec:
  type: NodePort
  selector:
    app: example-app
  ports:
      - nodePort: 30001
        name: http
        port: 5000
        targetPort: 5000