apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  releaseName: postgresql
  interval: 1h
  chart:
    spec:
      chart: postgresql
      version: 16.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: infrastructure
  values:
    global:
      postgresql:
        auth:
          database: testdb
          username: admin
          existingSecret: postgresql-secret
    primary:
      persistence:
        enabled: true
        size: 2Gi
      service:
        type: NodePort
        ports: 
          postgresql: 5432
        nodePorts:
          postgresql: 30011
