apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret        # Name of the secret
  namespace: postgresql          # Namespace where the secret will be stored
type: Opaque
data:
  password: YWRtaW4xMjM=  # Base64 encoded "admin123"