apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: example-app
  namespace: infrastructure
spec:
  image: ghcr.io/ben3dek/bened3k-psac/example-app
  interval: 1m
  accessFrom:
    namespaceSelectors:
      - matchLabels: {}