apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-release
  namespace: psac-gitops
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: 12.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
        namespace: psac-gitops
  interval: 1h
  values:
    postgresqlUsernameSecret:
      name: postgresql-secret
      key: postgresql-username
    postgresqlPasswordSecret:
      name: postgresql-secret
      key: postgresql-password
    postgresqlDatabase: psacdb 
    primary:
      persistence:
        enabled: true
        size: 2Gi
      service:
        type: NodePort                       # Service type
        port: 5432
        targetPort: 5432
        nodePort: 30011                     # Port for the PostgreSQL service
