name: Build and Push Docker Image

on:
  create:
    branches:
      - 'release/**'  # This triggers the workflow when a new release branch is created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker build environment
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to container registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          # Extract the branch name from the GitHub event
          branch_name=${{ github.ref_name }}

          version_name=$(echo $branch_name | cut -d'/' -f2)
          repo_name_lower=$(echo ${{ github.repository}} | tr '[:upper:]' '[:lower:]')
          
          docker build -t ghcr.io/$repo_name_lower/example-app:$version_name -f ./apps/example-app/source/Dockerfile .
          
      - name: Push Docker image
        run: |
          # Extract the branch name from the GitHub event
          branch_name=${{ github.ref_name }}

          version_name=$(echo $branch_name | cut -d'/' -f2)
          repo_name_lower=$(echo ${{ github.repository}} | tr '[:upper:]' '[:lower:]')

          docker push ghcr.io/$repo_name_lower/example-app:$version_name 
